"""PDF generation for match reports and cover letters.

Uses ReportLab's Platypus layout engine so text wraps and paginates properly
(the previous canvas approach truncated every line at 120 characters).
"""
from __future__ import annotations

import html
import re
from io import BytesIO
from typing import Dict, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

from utils.ats_scorer import is_section_header

INK = colors.HexColor("#1c1917")
MUTED = colors.HexColor("#78716c")
ACCENT = colors.HexColor("#b45309")
LINE = colors.HexColor("#e7e5e4")


def _styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "title", parent=base["Title"], fontName="Helvetica-Bold",
            fontSize=22, textColor=INK, spaceAfter=2, leading=26,
        ),
        "subtitle": ParagraphStyle(
            "subtitle", parent=base["Normal"], fontName="Helvetica",
            fontSize=10, textColor=MUTED, spaceAfter=14,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontName="Helvetica-Bold",
            fontSize=13, textColor=ACCENT, spaceBefore=14, spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"], fontName="Helvetica",
            fontSize=10.5, textColor=INK, leading=15, alignment=TA_LEFT,
            spaceAfter=6,
        ),
        "score": ParagraphStyle(
            "score", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=40, textColor=ACCENT, leading=44,
        ),
        "bullet": ParagraphStyle(
            "bullet", parent=base["Normal"], fontName="Helvetica",
            fontSize=10.5, textColor=INK, leading=15,
        ),
    }
    return styles


def _doc(target, title: str = "Resume Match Report") -> SimpleDocTemplate:
    """Build a document template writing to a path or a file-like buffer."""
    return SimpleDocTemplate(
        target, pagesize=A4,
        leftMargin=22 * mm, rightMargin=22 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
        title=title,
    )


# Exotic Unicode spaces the standard Helvetica font can't render in a PDF.
_ODD_SPACES = re.compile('[      ]')


def _esc(text: str) -> str:
    text = _ODD_SPACES.sub(" ", str(text))
    return html.escape(text).replace("\n", "<br/>")


def _skill_list(skills: List[str], styles) -> ListFlowable:
    if not skills:
        return Paragraph("<i>None identified.</i>", styles["body"])
    items = [ListItem(Paragraph(_esc(s), styles["bullet"]), leftIndent=6)
             for s in skills]
    return ListFlowable(items, bulletType="bullet", start="•",
                        bulletColor=ACCENT, leftIndent=12)


def export_analysis_to_pdf(record: Dict) -> bytes:
    """Render a structured analysis record to a styled PDF, returned as bytes.

    ``record`` is the normalized analysis dict (score, summary,
    matching_skills, missing_skills, suggestions, source).
    """
    buffer = BytesIO()
    styles = _styles()
    story = []

    story.append(Paragraph("Resume Match Report", styles["title"]))
    source = "AI analysis" if record.get("source") == "ai" else "Local analysis engine"
    story.append(Paragraph(f"Generated by AI Resume Matcher · {source}", styles["subtitle"]))
    story.append(HRFlowable(width="100%", color=LINE, thickness=1, spaceAfter=10))

    story.append(Paragraph("Match Score", styles["h2"]))
    story.append(Paragraph(f"{int(record.get('score', 0))}<font size=18>/100</font>", styles["score"]))
    if record.get("summary"):
        story.append(Spacer(1, 6))
        story.append(Paragraph(_esc(record["summary"]), styles["body"]))

    story.append(Paragraph("Matching Skills", styles["h2"]))
    story.append(_skill_list(record.get("matching_skills", []), styles))

    story.append(Paragraph("Missing Skills", styles["h2"]))
    story.append(_skill_list(record.get("missing_skills", []), styles))

    story.append(Paragraph("Suggestions", styles["h2"]))
    suggestions = record.get("suggestions", [])
    if suggestions:
        items = [ListItem(Paragraph(_esc(s), styles["bullet"]), leftIndent=6)
                 for s in suggestions]
        story.append(ListFlowable(items, bulletType="1", bulletColor=ACCENT,
                                  leftIndent=14))
    else:
        story.append(Paragraph("<i>No suggestions.</i>", styles["body"]))

    _doc(buffer).build(story)
    return buffer.getvalue()


def export_cover_letter_to_pdf(content: str) -> bytes:
    """Render a cover letter to a clean, letter-style PDF, returned as bytes.

    No title, subtitle, or "Generated by ..." branding: this is the file a
    candidate submits to an employer, so it reads as an ordinary letter
    starting directly with its own content, not a tool-generated artifact.
    """
    buffer = BytesIO()
    styles = _styles()
    story: List = []

    letter_style = ParagraphStyle(
        "letter", parent=styles["body"], fontSize=11, leading=17, spaceAfter=10,
    )
    for para in str(content).split("\n\n"):
        para = para.strip()
        if para:
            story.append(Paragraph(_esc(para), letter_style))

    _doc(buffer, title="Cover Letter").build(story)
    return buffer.getvalue()


def export_cv_to_pdf(cv_text: str) -> bytes:
    """Render a tailored CV to a styled PDF, returned as bytes.

    No title, subtitle, or "Generated by ..." branding: this is the file a
    candidate submits to an employer, so it reads as an ordinary resume
    starting directly with their own content, not a tool-generated artifact.
    Section header lines (SUMMARY, EXPERIENCE, EDUCATION, SKILLS, ...) get
    the ``h2`` style so the PDF keeps basic visual structure; everything
    else is grouped into body paragraphs, split on blank lines.
    """
    buffer = BytesIO()
    styles = _styles()
    story: List = []

    cv_style = ParagraphStyle(
        "cv_body", parent=styles["body"], fontSize=10.5, leading=15, spaceAfter=8,
    )

    def flush(buf: List[str]) -> None:
        text = "\n".join(buf).strip()
        if text:
            story.append(Paragraph(_esc(text), cv_style))
        buf.clear()

    para_buf: List[str] = []
    for line in str(cv_text).splitlines():
        if is_section_header(line):
            flush(para_buf)
            story.append(Paragraph(_esc(line.strip().upper()), styles["h2"]))
        elif not line.strip():
            flush(para_buf)
        else:
            para_buf.append(line)
    flush(para_buf)

    _doc(buffer, title="Resume").build(story)
    return buffer.getvalue()
